version: "3.3"                                                             
services:                                                                  
  elasticsearch:                                                           
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0             
    container_name: elasticsearch                                          
    volumes:                                                               
      - esdata:/usr/share/elasticsearch/data                               
    environment:                                                           
      - discovery.type=single-node                                         
    ports:                                                                 
      - "9300:9300"                                                        
      - "9200:9200"                                                        
                                                                           
  kibana:                                                                  
    image: docker.elastic.co/kibana/kibana:7.2.0                           
    container_name: kibana                                                 
    environment:                                                           
      - ELASTICSEARCH_URL=http://elasticsearch:9200                        
    links:                                                                 
      - "elasticsearch:elasticsearch"                                      
    ports:                                                                 
      - "5601:5601"                                                        
                                                                           
volumes:                                                                   
  esdata:                                                                  